### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by rinrab** [mr-Librian/Console-GIF#1]
When I run program with command in windows CMD

```bat
javac Main.java
java Main example.gif
```
It prints strange symbols to the output.

![image](https://github.com/mr-Librian/Console-GIF/assets/64201197/e74f7eff-ab92-4aaf-822e-17ac1a8169d0)

**Comment by mr-Librian** [comment]
Windows CMD does not support ANSI escape codes by default. Try running it in Windows Terminal.
